Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision :shell, inline: <<-SHELL
  	apt-get update
  	apt-get install snapd -y
  	systemctl enable snapd
  	systemctl start snapd
  SHELL
end
